### ISSUE TITLE
NDK not configured

### ISSUE THREAD

**Issue by wwdok** [widlyGod/card_tracking#1]
请问您知道怎么解决吗？ 我明明已经更新NDK了，它还是找不到
![image](https://user-images.githubusercontent.com/43233772/100497468-bbc46d80-3196-11eb-9f01-5f8a4a4d5d82.png)

**Comment by widlyGod** [comment]
请确保改路径下有该ndk版本及其完整性。
确认 SDK Manager->SDK Tools->NDK 选中。

**Comment by wwdok** [comment]
重启后就好了
